services:
  back-end:
    build:
      context: .
      dockerfile: ./Dockerfile.jvm
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080"]
      interval: 5s
      timeout: 5s
      retries: 5
    extra_hosts:
      - host.docker.internal:host-gateway
